language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ravinder/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ravinder/react-test npm run test

after_success:
  - docker build -t ravinderdock/multi-client ./client
  - docker build -t ravinderdock/multi-server ./server
  - docker build -t ravinderdock/multi-nginx ./nginx
  - docker build -t ravinderdock/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # images push to dockerhub
  - docker push ravinderdock/multi-client
  - docker push ravinderdock/multi-server
  - docker push ravinderdock/multi-nginx
  - docker push ravinderdock/multi-worker

deploy:
 provider: elasticbeanstalk
 region: 'us-east-2'
 app: 'multi-docker'
 env: 'Multidocker-env'
 bucket_name: 'elasticbeanstalk-us-east-2-535111072532'
 bucket_path: 'docker-multi'
 on:
   branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY
